global:
  scrape_interval: 15s   # Как часто Prometheus будет собирать метрики (по умолчанию 15 секунд).
  evaluation_interval: 15s   # Как часто Prometheus будет оценивать правила алертинга.

# Настройки Alertmanager.
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'   # Адрес Alertmanager.

# Правила алертинга.
rule_files:
  - 'alert_rules.yml'   # Файл с правилами алертинга.

# Настройки remote read/write.
remote_write:
  - url: 'http://remote-storage:8086/write'   # Куда отправлять метрики (например, в Thanos, Cortex или Mimir).
    queue_config:
      capacity: 10000   # Максимальное количество метрик в очереди.
remote_read:
  - url: 'http://remote-storage:8086/read'   # Откуда читать метрики (например, из Thanos, Cortex или Mimir).

# Конфигурация сбора метрик (scrape_configs).
scrape_configs:
  # Конфигурация для Node Exporter.
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ip_adderess:9100']   # Адрес Node Exporter.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'ip_adderess:9100'   # Адрес Node Exporter.

  # Конфигурация для Process Exporter.
  - job_name: 'process_exporter'
    static_configs:
      - targets: ['ip_adderess:9256']   # Адрес Process Exporter.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'ip_adderess:9256'   # Адрес Process Exporter.

  # Конфигурация для Blackbox Exporter.
  - job_name: 'blackbox_exporter'
    metrics_path: /probe   # Путь к метрикам Blackbox Exporter.
    params:
      module: [http_2xx]   # Модуль для проверки HTTP-запросов.
    static_configs:
      - targets:
          - 'http://example.com'   # Цель для проверки (например, веб-сайт).
          - 'http://another-example.com'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'ip_adderess:9115'   # Адрес Blackbox Exporter.
